defmodule StaticContext.Validate do
  @moduledoc """
  Validation helpers used by the EEx templates in `priv/templates/static_context/`.

  These functions are called at runtime from code generated by `StaticContext`.
  They guard against unknown struct keys in filter clauses like `list_by/1`
  and `get_by/1`.
  """

  @doc """
  Validates that all keys in `clauses` are valid fields of `struct_module`.

  Raises `ArgumentError` listing unknown keys if any are found.
  """
  @spec validate_clauses!(module(), keyword()) :: :ok
  def validate_clauses!(struct_module, clauses) do
    valid_keys = struct_module.__struct__() |> Map.keys() |> Enum.reject(&(&1 == :__struct__))
    invalid_keys = Keyword.keys(clauses) -- valid_keys

    if Enum.any?(invalid_keys) do
      raise ArgumentError, """
      Unknown key(s) #{inspect(invalid_keys)} for #{struct_module}.
      Valid keys are: #{inspect(valid_keys)}
      """
    end

    :ok
  end
end
